### ISSUE TITLE
Could you kindly provide ROS bag for testing? Your assistance would be greatly appreciated.

### ISSUE THREAD

**Issue by LiuHahahaha** [Ikhyeon-Cho/height_mapping#1]
Excellent work! Could you kindly provide ROS bag for testing? Your assistance would be greatly appreciated.

**Comment by Ikhyeon-Cho** [comment]
@LiuHahahaha Hi, I apologies for the delayed response—recently, I had some personal matters to attend to.

For testing with rosbag, the [urban-traversability-dataset](https://github.com/Ikhyeon-Cho/urban-traversability-dataset) repo which I released might be a great starting point. 
It includes several rosbag files designed for testing and validating terrain mapping in urban environments. Since these files have been extensively tested, they might be beneficial for your use case.

If you have any questions or specific requirements, feel free to reach out.
